### ISSUE TITLE
Footer as CC rather than copyright?

### ISSUE THREAD

**Issue by coevolving** [cgmartin/hexo-theme-bootstrap-blog#11]
Thanks for providing this bootstrap-blog theme.

In the spirit of open sourcing, should there be an easy option to set the licensing for the blog as some form of Creative Commons licensing?  The default of a copyright means that, technically, anyone who wants to reproduce the content has to contact the original author for a release, first.  Having a Creative Commons license asserts the intentions of the author in sharing (and allowing redistribution and derivations) of the content.

**Comment by cgmartin** [comment]
Feel free to change to your taste of licensing.
